name: ROS2 humble Linux CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
          path: ros2_ws/src/vehicle_insterfaces
    - name: Install Ros2
      run: |
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install curl -y
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt upgrade
          sudo apt install ros-humble-ros-base
          sudo apt-get install --no-install-recommends -y $(cat requirement_apt.txt) | xargs
    - name: Build
      run: |
          cd ros2_ws
          source /opt/ros/humble/setup.bash && colcon build --symlink-install
          cd .
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: ros2_ws
              
